# Generated by Django 3.2.4 on 2022-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_prettynum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
